### ISSUE TITLE
Toutes les mécaniques de jeu sont intégrées

### ISSUE THREAD

**Issue by saundersp** [RemiFELIN/7Wonders_By_Miagestics#46]
- [x] Les effets des merveilles sont intégrés ( #44 ) 
- [x] Joueur score : calcul des point de victoire de batîments commerciaux (Voir 6. de la page 6 des régles)  ( #43 ) 
- [x] Joueur score : calcul des scores de guildes
- [x] PoserCarte : ajout systéme de baîtment suivant ( #42, #52 )
